name: deploy-application

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'provision-infrastructure'
    types:
      - completed
    branches:
      - 'main'

jobs:
  deploy_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          chmod +x ${GITHUB_WORKSPACE}/deploy/application/push-image.sh
          chmod +x ${GITHUB_WORKSPACE}/deploy/application/deploy.sh
          ${GITHUB_WORKSPACE}/deploy/application/push-image.sh
          ${GITHUB_WORKSPACE}/deploy/application/deploy.sh
