name: deploy-application

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'provision-infrastructure'
    types:
      - completed
    branches:
      - 'main'

jobs:
  deploy_application:
    runs-on: ubuntu-latest
    env:
      PREFIX: wu-az-capp
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "ACR_URL=$(az acr list -g ${{ env.PREFIX }} --query "[].loginServer" -o tsv)" >> $GITHUB_ENV
          echo "ACR_USERNAME=$(az keyvault secret show --vault-name ${{ env.PREFIX }}-kv --name AcrPushServicePrincipalAppId --query "value" -o tsv)" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(az keyvault secret show --vault-name ${{ env.PREFIX }}-kv --name AcrPushServicePrincipalPassword --query "value" -o tsv)" >> $GITHUB_ENV
          echo "ACR_IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.ACR_URL }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: src/AzCappHttp/Dockerfile
        push: true
        tags: ${{ env.ACR_URL }}/${{ env.PREFIX }}-http:${{ env.ACR_IMAGE_TAG }},${{ env.ACR_URL }}/${{ env.PREFIX }}-http:latest
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          chmod +x ${GITHUB_WORKSPACE}/deploy/application/deploy.sh
          ${GITHUB_WORKSPACE}/deploy/application/deploy.sh
